Update workflows

diff --git a/.github/workflows/update-package.yaml b/.github/workflows/update-package.yaml
--- a/.github/workflows/update-package.yaml
+++ b/.github/workflows/update-package.yaml
@@ -1,28 +1,46 @@
-name: Build image and push to container registry
+name: Update package
 
 on:
   workflow_call:
   workflow_dispatch:
 
 jobs:
-  build-and-push:
+  check-tag:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.repository.default_branch }}
-          fetch-depth: 50
+          fetch-depth: 0
+
+      - name: Check tag
+        run: |
+          if git tag --points-at HEAD | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
+            exit 0
+          fi
+          echo "ERROR: There needs to be a version tag."
+          exit 1
+
+  update-package:
+    runs-on: ubuntu-latest
+    needs:
+      - check-tag
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.repository.default_branch }}
+          fetch-depth: 0
 
       - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+        uses: docker/setup-qemu-action@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+      - name: Set up Buildx
+        uses: docker/setup-buildx-action@v3
 
-      - name: Login to GitHub container registry
-        uses: docker/login-action@v2
+      - name: Login to container registry
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
@@ -31,15 +49,14 @@ jobs:
       - name: Prepare tags
         id: tags
         run: |
-          git fetch --all --tags
           echo "DIGEST=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
           echo "REF_NAME=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
 
-      - name: Build image and push to container registry
-        uses: docker/build-push-action@v4
+      - name: Update package
+        uses: docker/build-push-action@v5
         with:
           context: .
-          platforms: linux/amd64,linux/arm64
+          platforms: linux/amd64,linux/arm64/v8
           push: true
           tags: |
             ${{ format('ghcr.io/{0}:{1}', github.repository, steps.tags.outputs.DIGEST) }}
